version: '3'

services:
    django:
        build:
            context: .
            dockerfile: .conf/Dockerfile
        ports:
          - "5432:5432"
          - "80:80"
        volumes:
          - ./ppomppu/.secret:/srv/app/ppomppu/.secret
          - ./ppomppu/conf:/srv/app/ppomppu/conf
