# Generated by Django 2.1.7 on 2019-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190504_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
