# Generated by Django 2.1.5 on 2019-01-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_data', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='update_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling_data.CrawlingData'),
        ),
    ]
